# Site settings
title: Project COMRAT
description: Let's build our own digital infrascructure ourselves
email: projectcomrat@gmail.com
baseurl: /
url: "http://project-comrat.github.io" # the base hostname & protocol for your site
#favicon
favicon: /favicon.png

#feed
feedburner_username: project-comrat
#twitter
twitter_username: project-comrat
github_username:  project-comrat

#linkedin
linkedin_username: project-comrat

#google analytics
google_analytics_id : 
#gplus
gplus_username: 

#fb_username
fb_username: project-comrat

#permalink /blog/2014/11/11/this-is-a-sample-post
permalink: /blog/:year/:month/:day/:title
# Build settings
markdown: kramdown

#Disqus configuration
disqus_short_name: project-comrat
disqus_show_comment_count: true

#Can be used for multiple author blogs ! Add name to post For more visit the sample
authors:
  pranavrajs:
    display_name: Sudaraka Jayathilaka
    email: sudarakayasindu@gmail.com
    fb: sudara.yasi
    linkedin: sudaraka94
    twitter: sudaraka94
    github: sudaraka94
